version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
     - ./volumes:/var/lib/grafana
    user: "472:472"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus-data:/prometheus/data
      - ./volumes/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml  # Mount local Prometheus config
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/data"
      - "--storage.tsdb.retention.time=30d"              #儲存時間
    depends_on:
      - snmp-exporter
    networks:
      - monitoring

  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: unless-stopped
    ports:
      - "9116:9116"
    volumes:
      - ./volumes/snmp-exporter-config/snmp.yml:/etc/snmp_exporter/snmp.yml
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
    driver: bridge
