global:
  scrape_interval: 1s  # 每秒抓取數
  evaluation_interval: 10s  # 每秒評估(警報)

scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 10.100.255.254  # SNMP IP
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.110.0.57:9116  # 本機IP:9116

